categories:
  Friends:
    bergfreunde: https://www.bergfreunde.eu/camming-devices-friends/
    mountex: https://mountex.hu/sziklamaszas-hegymaszas?v=115
  Slings:
    bergfreunde: https://www.bergfreunde.eu/slings-cord/
    mountex: https://mountex.hu/sziklamaszas-hegymaszas?v=110
  Ropes:
    bergfreunde: https://www.bergfreunde.eu/climbing-ropes/
    mountex: https://mountex.hu/sziklamaszas-hegymaszas?v=109
  Carabiners:
    bergfreunde: https://www.bergfreunde.eu/carabiners-quickdraws/
    mountex: https://mountex.hu/sziklamaszas-hegymaszas?v=107