sites:
  - name: bergfreunde
    url: https://www.bergfreunde.eu/
    enabled: false
  - name: mountex
    url: https://mountex.hu/
    enabled: false
  - name: 4camping
    url: https://www.4camping.hu/
    enabled: true