name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Kill running container
        run: |
          echo "Killing running container"
          docker rm -f climbing-stuff_app || true

      - name: Build and start containers
        run: |
          echo "Building and starting containers"
          docker-compose up -d --build
